#!/bin/bash
set -euxo pipefail

# create temporary directory
WORK=$(mktemp -d)
cd $WORK

# extract sources
__pkg_name=tzdata
__pkg_version=2023c
pkg_name=${__pkg_name}${__pkg_version}
tar -xf /usr/src/$pkg_name.tar.gz

# create temporary destination dir
DESTDIR=$WORK/___destdir___
/sbin/pkg-mkskel $DESTDIR

# install package into the temporary destination dir
ZONEINFO=$DESTDIR/usr/share/zoneinfo
mkdir -pv $ZONEINFO/{posix,right}

for tz in etcetera southamerica northamerica europe africa antarctica asia australasia backward; do
	zic -L /dev/null -d $ZONEINFO ${tz}
	zic -L /dev/null -d $ZONEINFO/posix ${tz}
	zic -L leapseconds -d $ZONEINFO/right ${tz}
done

cp -v zone.tab zone1970.tab iso3166.tab $ZONEINFO
zic -d $ZONEINFO -p America/New_York
unset ZONEINFO

# create package manifest
/sbin/pkg-mkmanifest $DESTDIR ${__pkg_name}-${__pkg_version}

# install the actual package in the root
/sbin/pkg-install $DESTDIR

# run the post installation script
ln -sfv /usr/share/zoneinfo/Europe/Rome /etc/localtime

# remove temporary dir
rm -rf $WORK
