#!/bin/bash
set -euxo pipefail

# create temporary directory
WORK=$(mktemp -d)
cd $WORK

# extract sources
pkg_name=iana-etc-20230810
tar -xf /usr/src/$pkg_name.tar.gz
cd $pkg_name

# prepare the package
# nothing!

# create temporary destination dir
DESTDIR=$WORK/___destdir___
/sbin/pkg-mkskel $DESTDIR

# install package into the temporary destination dir
cp services $DESTDIR/etc/services
cp protocols $DESTDIR/etc/protocols

# create package manifest
/sbin/pkg-mkmanifest $DESTDIR $pkg_name

# install the actual package in the root
/sbin/pkg-install $DESTDIR

# remove temporary dir
rm -rf $WORK
