#!/bin/bash
set -euxo pipefail

if [[ $# != 1 ]]; then
	echo "usage: $0 pkgdir" 1>&2
	exit 1
fi

# make sure we're not going to overwrite configuration files by default
(cd $1 && find ./etc ./usr/lib/tmpfiles.d/ ./usr/lib/systemd/system -type f -exec mv {} {}.new \;)

# create inline archive and extract to root directory
tar -C $1 -cf- . | tar -C / -xvf-

# make sure we do not keep .new files around unless they're needed
for entry_dot_new in $(find /etc /usr/lib/tmpfiles.d/ /usr/lib/systemd/system/ -type f -name \*.new); do
	entry=${entry_dot_new%%.new}

	# if there's no pre-existing entry or the entry size is
	# zero, then just just move the new file in place
	if [[ ! -s $entry ]]; then
		mv $entry_dot_new $entry
		continue
	fi

	# if there are no changes, zap the .new file
	if cmp $entry $entry_dot_new; then
		rm $entry_dot_new
		continue
	fi
done

# make sure we update symbolic links
/sbin/ldconfig
