#!/bin/bash
set -euxo pipefail

# create temporary directory
WORK=$(mktemp -d)
cd $WORK

# extract sources
pkg_name=grep-3.11
tar -xf /usr/src/$pkg_name.tar.xz
cd $pkg_name

# prepare the package
sed -i "s/echo/#echo/" src/egrep.sh

./configure --prefix=/usr

make -j$(nproc)

# create temporary destination dir
DESTDIR=$WORK/___destdir___
/sbin/pkg-mkskel $DESTDIR

# install package into the temporary destination dir
make DESTDIR=$DESTDIR install

# create package manifest
/sbin/pkg-mkmanifest $DESTDIR $pkg_name

# install the actual package in the root
/sbin/pkg-install $DESTDIR

# remove temporary dir
rm -rf $WORK
