#!/bin/bash
set -euxo pipefail

# create temporary directory
WORK=$(mktemp -d)
cd $WORK

# extract sources
pkg_name=flex-2.6.4
tar -xf /usr/src/$pkg_name.tar.gz
cd $pkg_name

# prepare the package
./configure --prefix=/usr \
	--docdir=/usr/share/doc/flex-2.6.4 \
	--disable-static

make -j$(nproc)

# create temporary destination dir
DESTDIR=$WORK/___destdir___
/sbin/pkg-mkskel $DESTDIR

# install package into the temporary destination dir
make DESTDIR=$DESTDIR install

ln -sv flex $DESTDIR/usr/bin/lex

ln -sv flex.1 $DESTDIR/usr/share/man/man1/lex.1

# create package manifest
/sbin/pkg-mkmanifest $DESTDIR $pkg_name

# install the actual package in the root
/sbin/pkg-install $DESTDIR

# remove temporary dir
rm -rf $WORK
