#!/bin/bash
set -euxo pipefail

# create temporary directory
WORK=$(mktemp -d)
cd $WORK

# extract sources
pkg_name=bzip2-1.0.8
tar -xf /usr/src/$pkg_name.tar.gz
cd $pkg_name

# prepare the package
patch -Np1 -i /usr/src/bzip2-1.0.8-install_docs-1.patch

sed -i 's@\(ln -s -f \)$(PREFIX)/bin/@\1@' Makefile

sed -i "s@(PREFIX)/man@(PREFIX)/share/man@g" Makefile

make -j$(nproc) -f Makefile-libbz2_so
make clean

make -j$(nproc)

# create temporary destination dir
DESTDIR=$WORK/___destdir___
/sbin/pkg-mkskel $DESTDIR

# install package into the temporary destination dir
make PREFIX=$DESTDIR/usr install

cp -av libbz2.so.* $DESTDIR/usr/lib
ln -sv libbz2.so.1.0.8 $DESTDIR/usr/lib/libbz2.so

cp -v bzip2-shared $DESTDIR/usr/bin/bzip2
for i in $DESTDIR/usr/bin/{bzcat,bunzip2}; do
	ln -sfv bzip2 $i
done

rm -fv $DESTDIR/usr/lib/libbz2.a

# create package manifest
/sbin/pkg-mkmanifest $DESTDIR $pkg_name

# install the actual package in the root
/sbin/pkg-install $DESTDIR

# remove temporary dir
rm -rf $WORK
