#!/bin/bash
set -euxo pipefail

# run the preinstallation script
install -v -g sys -m700 -d /var/lib/sshd

if ! getent group sshd 2>/dev/null; then
	groupadd -g 50 sshd
	useradd -c 'sshd PrivSep' \
		-d /var/lib/sshd \
		-g sshd \
		-s /bin/false \
		-u 50 sshd
fi

# create temporary directory
WORK=$(mktemp -d)
cd $WORK

# extract sources
pkg_name=openssh-9.6p1
tar -xf /usr/src/$pkg_name.tar.gz
cd $pkg_name

# prepare the package
./configure --prefix=/usr \
	--sysconfdir=/etc/ssh \
	--with-privsep-path=/var/lib/sshd \
	--with-default-path=/usr/bin \
	--with-superuser-path=/usr/sbin:/usr/bin \
	--with-pid-dir=/run

make -j$(nproc)

# create temporary destination dir
DESTDIR=$WORK/___destdir___
/sbin/pkg-mkskel $DESTDIR

# install package into the temporary destination dir
make DESTDIR=$DESTDIR install

find $DESTDIR/etc -type f -exec mv {} {}.new \;

# create package manifest
/sbin/pkg-mkmanifest $DESTDIR $pkg_name

echo './var/lib/sshd/' >>/var/lib/pkg-tools/manifest/$pkg_name.txt
echo './var/mail/sshd' >>/var/lib/pkg-tools/manifest/$pkg_name.txt

# install the actual package in the root
/sbin/pkg-install $DESTDIR

# remove temporary dir
rm -rf $WORK
