#!/bin/bash
set -euxo pipefail

# create temporary directory
WORK=$(mktemp -d)
cd $WORK

# extract sources
pkg_name=git-2.41.0
tar -xf /usr/src/$pkg_name.tar.xz
cd $pkg_name

# prepare the package
./configure --prefix=/usr \
	--with-gitconfig=/etc/gitconfig \
	--with-python=python3

make -j$(nproc)

# create temporary destination dir
DESTDIR=$WORK/___destdir___
/sbin/pkg-mkskel $DESTDIR

# install package into the temporary destination dir
make DESTDIR=$DESTDIR perllibdir=/usr/lib/perl5/5.38/site_perl install

find $DESTDIR/etc -type f -exec mv {} {}.new \;

# create package manifest
/sbin/pkg-mkmanifest $DESTDIR $pkg_name

# install the actual package in the root
/sbin/pkg-install $DESTDIR

# remove temporary dir
rm -rf $WORK
