#!/bin/bash
set -euxo pipefail

# create temporary directory
WORK=$(mktemp -d)
cd $WORK

# extract sources
pkg_name=libxcrypt-4.4.36
tar -xf /usr/src/$pkg_name.tar.xz
cd $pkg_name

# prepare the package
./configure --prefix=/usr \
	--enable-hashes=strong,glibc \
	--enable-obsolete-api=no \
	--disable-static \
	--disable-failure-tokens

make -j$(nproc)

# create temporary destination dir
DESTDIR=$WORK/___destdir___
/sbin/pkg-mkskel $DESTDIR

# install package into the temporary destination dir
make DESTDIR=$DESTDIR install

# create package manifest
/sbin/pkg-mkmanifest $DESTDIR $pkg_name

# install the actual package in the root
/sbin/pkg-install $DESTDIR

# remove temporary dir
rm -rf $WORK
