#!/bin/bash
set -euxo pipefail

# create temporary directory
WORK=$(mktemp -d)
cd $WORK

# extract sources
pkg_name=perl-5.38.0
tar -xf /usr/src/$pkg_name.tar.xz
cd $pkg_name

# prepare the package
sh Configure -des \
	-Dprefix=/usr \
	-Dvendorprefix=/usr \
	-Dprivlib=/usr/lib/perl5/5.38/core_perl \
	-Darchlib=/usr/lib/perl5/5.38/core_perl \
	-Dsitelib=/usr/lib/perl5/5.38/site_perl \
	-Dsitearch=/usr/lib/perl5/5.38/site_perl \
	-Dvendorlib=/usr/lib/perl5/5.38/vendor_perl \
	-Dvendorarch=/usr/lib/perl5/5.38/vendor_perl \
	-Dman1dir=/usr/share/man/man1 \
	-Dman3dir=/usr/share/man/man3 \
	-Dpager="/usr/bin/less -isR" \
	-Duseshrplib \
	-Dusethreads

make -j$(nproc)

# create temporary destination dir
DESTDIR=$WORK/___destdir___
/sbin/pkg-mkskel $DESTDIR

# install package into the temporary destination dir
make DESTDIR=$DESTDIR install

# create package manifest
/sbin/pkg-mkmanifest $DESTDIR $pkg_name

# install the actual package in the root
/sbin/pkg-install $DESTDIR

# remove temporary dir
rm -rf $WORK
