#!/bin/bash
set -euxo pipefail

# create temporary directory
WORK=$(mktemp -d)
cd $WORK

# extract sources
pkg_name=sudo-1.9.14p3
tar -xf /usr/src/$pkg_name.tar.gz
cd $pkg_name

# prepare the package
./configure --prefix=/usr \
	--libexecdir=/usr/lib \
	--with-secure-path \
	--with-all-insults \
	--with-env-editor \
	--docdir=/usr/share/doc/sudo-1.9.14p3 \
	--with-passprompt="[sudo] password for %p: "

make -j$(nproc)

# create temporary destination dir
DESTDIR=$WORK/___destdir___
/sbin/pkg-mkskel $DESTDIR

# install package into the temporary destination dir
make DESTDIR=$DESTDIR install

ln -sfv libsudo_util.so.0.0.0 $DESTDIR/usr/lib/sudo/libsudo_util.so.0

find $DESTDIR/etc -type f -exec mv {} {}.new \;

# create package manifest
/sbin/pkg-mkmanifest $DESTDIR $pkg_name

# install the actual package in the root
/sbin/pkg-install $DESTDIR

# remove temporary dir
rm -rf $WORK
