#!/bin/bash
set -euxo pipefail

# create temporary directory
WORK=$(mktemp -d)
cd $WORK

# extract sources
pkg_name=meson-1.2.1
tar -xf /usr/src/$pkg_name.tar.gz
cd $pkg_name

# prepare the package
pip3 wheel -w dist --no-build-isolation --no-deps $PWD

# create temporary destination dir
DESTDIR=$WORK/___destdir___
/sbin/pkg-mkskel $DESTDIR

# install package into the temporary destination dir
pip3 install --no-index --find-links dist --root=$DESTDIR meson

install -d $DESTDIR/usr/share/bash-completion/completions/
install -vDm644 data/shell-completions/bash/meson $DESTDIR/usr/share/bash-completion/completions/meson

install -d $DESTDIR/usr/share/zsh/site-functions/
install -vDm644 data/shell-completions/zsh/_meson $DESTDIR/usr/share/zsh/site-functions/_meson

# create package manifest
/sbin/pkg-mkmanifest $DESTDIR $pkg_name

# install the actual package in the root
/sbin/pkg-install $DESTDIR

# remove temporary dir
rm -rf $WORK
