#!/bin/bash
set -euxo pipefail

if [[ $# != 1 ]]; then
	echo "usage: $0 pkgdir" 1>&2
	exit 1
fi

# make sure we're not going to overwrite configuration files by default
for dir in $1/etc $1/usr/lib/tmpfiles.d $1/usr/lib/systemd/system; do
	if [[ ! -d $dir ]]; then
		continue
	fi
	find $dir -type f -exec mv {} {}.new \;
done

# strip binaries before installing them
for dir in $1/usr/{bin,lib,libexec,sbin}; do
	for file in $(find $dir -type f); do
		if readelf -h $file >/dev/null 2>&1; then
			strip -g $file
		fi
	done
done

# create inline archive and extract to root directory
tar -C $1 -cf- . | tar -C / -xvf-

# make sure we do not keep .new files around unless they're needed
for entry_dot_new in $(find /etc /usr/lib/tmpfiles.d/ /usr/lib/systemd/system/ -type f -name \*.new); do
	entry=${entry_dot_new%%.new}

	# if there's no pre-existing entry or the entry size is
	# zero, then just just move the new file in place
	if [[ ! -s $entry ]]; then
		mv $entry_dot_new $entry
		continue
	fi

	# if there are no changes, zap the .new file
	if cmp $entry $entry_dot_new; then
		rm $entry_dot_new
		continue
	fi
done

# make sure we update symbolic links
/sbin/ldconfig
