#!/bin/bash
set -euxo pipefail

# create temporary directory
WORK=$(mktemp -d)
cd $WORK

# extract sources
pkg_name=bash-5.2.15
tar -xf /usr/src/$pkg_name.tar.gz
cd $pkg_name

# prepare the package
./configure --prefix=/usr \
	--without-bash-malloc \
	--with-installed-readline \
	--docdir=/usr/share/doc/bash-5.2.15

make -j$(nproc)

# create temporary destination dir
DESTDIR=$WORK/___destdir___
/sbin/pkg-mkskel $DESTDIR

# install package into the temporary destination dir
make DESTDIR=$DESTDIR install

ln -sf sh $DESTDIR/usr/bin/bash

# create package manifest
/sbin/pkg-mkmanifest $DESTDIR $pkg_name

# install the actual package in the root
/sbin/pkg-install $DESTDIR

# remove temporary dir
rm -rf $WORK
