#!/bin/bash
set -euxo pipefail

# create temporary directory
WORK=$(mktemp -d)
cd $WORK

# extract sources
pkg_name=kmod-30
tar -xf /usr/src/$pkg_name.tar.xz
cd $pkg_name

# prepare the package
./configure --prefix=/usr \
	--sysconfdir=/etc \
	--with-openssl \
	--with-xz \
	--with-zstd \
	--with-zlib

make -j$(nproc)

# create temporary destination dir
DESTDIR=$WORK/___destdir___
/sbin/pkg-mkskel $DESTDIR

# install package into the temporary destination dir
make DESTDIR=$DESTDIR install

for target in depmod insmod modinfo modprobe rmmod; do
	ln -sfv ../bin/kmod $DESTDIR/usr/sbin/$target
done

ln -sfv kmod $DESTDIR/usr/bin/lsmod

# create package manifest
/sbin/pkg-mkmanifest $DESTDIR $pkg_name

# install the actual package in the root
/sbin/pkg-install $DESTDIR

# remove temporary dir
rm -rf $WORK
