#!/bin/bash
set -euxo pipefail

# TODO: keep in sync with stage1-001-create-skel.bash
util_create_skel() {
	local destdir=$1

	mkdir -pv $destdir/{etc,var} $destdir/usr/{bin,lib,sbin} $destdir/opt

	for i in bin lib sbin; do
		ln -sv usr/$i $destdir/$i
	done

	case $(uname -m) in
	x86_64)
		mkdir -pv $destdir/lib64
		;;
	esac
}

if [[ $# != 1 ]]; then
	echo "usage: $0 pkgdir" 1>&2
	exit 1
fi

util_create_skel $1
