#!/bin/bash
set -euxo pipefail

cd /tmp
tar -xf /usr/src/util-linux-2.39.1.tar.xz
cd util-linux-2.39.1

mkdir -pv /var/lib/hwclock

# register the creation of /var/lib/hwclock
(cd / && find ./var/lib/hwclock -ls) >/var/lib/pkg-tools/manifest/aaa-var-lib-hwclock.txt

./configure ADJTIME_PATH=/var/lib/hwclock/adjtime \
	--libdir=/usr/lib \
	--runstatedir=/run \
	--docdir=/usr/share/doc/util-linux-2.39.1 \
	--disable-chfn-chsh \
	--disable-login \
	--disable-nologin \
	--disable-su \
	--disable-setpriv \
	--disable-runuser \
	--disable-pylibmount \
	--disable-static \
	--without-python

make -j$(nproc)

make install

cd /tmp
rm -rf /tmp/util-linux-2.39.1
