#!/bin/bash
set -euxo pipefail

cd /tmp
tar -xf /usr/src/bison-3.8.2.tar.xz
cd bison-3.8.2
./configure --prefix=/usr --docdir=/usr/share/doc/bison-3.8.2
make -j$(nproc)
make install
cd /tmp
rm -rf /tmp/bison-3.8.2
