#!/bin/bash
set -euxo pipefail

cd /tmp
tar -xf /usr/src/perl-5.38.2.tar.gz
cd perl-5.38.2

sh Configure -des \
	-Dprefix=/usr \
	-Dvendorprefix=/usr \
	-Duseshrplib \
	-Dprivlib=/usr/lib/perl5/5.38/core_perl \
	-Darchlib=/usr/lib/perl5/5.38/core_perl \
	-Dsitelib=/usr/lib/perl5/5.38/site_perl \
	-Dsitearch=/usr/lib/perl5/5.38/site_perl \
	-Dvendorlib=/usr/lib/perl5/5.38/vendor_perl \
	-Dvendorarch=/usr/lib/perl5/5.38/vendor_perl

make -j$(nproc)

make install

cd /tmp
rm -rf /tmp/perl-5.38.2
